### ISSUE TITLE
describe-function randomly stops working

### ISSUE THREAD

**Issue by ylluminarious** [DarwinAwardWinner/ido-completing-read-plus#144]
Sometimes, inexplicably, and randomly I lose ido completion for `describe-function`. It only happens for this command, as far as I can tell. It is happening right now. I can solve the problem by restarting Emacs, but that is the only way I know how to do it. All other commands *seem* to be working fine with ido completion, including `describe-variable`. Unfortunately, I can't restart my Emacs session right now since I have a lot of stuff open.

Version info:

```
GNU Emacs 25.3.3 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2017-09-28
```

Also, I'm using the Emacs Mac Port by Yamamoto Mitsuharu.

**Comment by DarwinAwardWinner** [comment]
Can you enable `ido-cr+-debug-mode` and tell me what it says in the `*Messages*` buffer when you run `describe-function`?

**Comment by ylluminarious** [comment]
@DarwinAwardWinner 
```
ido-completing-read+: Falling back to ‘completing-read-default’ because there are more than 30000 items in COLLECTION (see `ido-cr+-max-items').
```
I think I understand what this is saying, but I'm not sure why it's saying that.

**Comment by DarwinAwardWinner** [comment]
It's telling you that the number of completions is more than `ido-cr+-max-items`, and it's falling back to non-ido completion for the sake of performance. 30000 is the default, but you can set it to whatever you like, as long as it doesn't slow down you your computer.

**Comment by ylluminarious** [comment]
@DarwinAwardWinner Right, I understand that. I just mean that I don't understand *how* my completion list for `describe-function` got to be so big... this issue has never happened until quite recently.

**Comment by DarwinAwardWinner** [comment]
Perhaps you recently installed some new packages in your config? Keep in mind that the number of completions for `describe-function` depends on which libraries you currently have loaded, and that in recent Emacs versions, it auto-loads libraries that match the prefix you have typed in order to offer completions for functions matching that prefix. So it makes sense that once you have triggered the loading of enough libraries by using their autoloaded functions, the total number of defined functions exceeds 30000 and triggers the large collection fallback. 

For what it's worth, on my Emacs right now, `(length (all-completions "" obarray 'fboundp))` returns 22863, so exceeding 30000 does not seem implausible to me.

**Comment by ylluminarious** [comment]
@DarwinAwardWinner Thanks for the info. While I have not installed new packages recently, it is certainly possible that I've caused some other funky things to happen which could overpopulate my `ido-cr+-max-items`. Sometimes I feel like I push Emacs too hard...

**Comment by DarwinAwardWinner** [comment]
Well, like I said, 30k is probably overly conservative for recent hardware. You could probably set it a lot higher without too much slowdown. Give 50k a try and if it's too slow, set it back to 30k and accept the fallback.

**Comment by ylluminarious** [comment]
@DarwinAwardWinner Alright, thanks once again for the advice. And thanks also for this package... I feel like I'm too reliant on it sometimes ;)
